### ISSUE TITLE
Eclipse java style does not specify space between import groups

### ISSUE THREAD

**Issue by bentatham** [google/styleguide#724] opened 2022-11-09 14:57 UTC
As per the Java Style Guide:

> If there are both static and non-static imports, a single blank line separates the two blocks. 

But the [eclipse-java-google-style.xml](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml) specifies a value of 0, when it should be 1.

```
<setting id="org.eclipse.jdt.core.formatter.blank_lines_between_import_groups" value="0"/>
```

It seems that the Google formatter implementation for Eclipse does not organize imports, so you have to separately configure the Organize Imports ordering in Eclipse settings, but then this value removes the line between static and non-static imports.

**Comment by florianlacreuse** [comment] 2024-07-03 08:25
I agree with you but this is a duplicate of #273 and there is an open PR #279.

**Closed as completed** 2024-07-03 11:41 UTC
Labels: duplicate
